import { describe, expect, it } from "vitest";
import { sqliteDdlToPostgres, translateToPostgres } from "../src/sql.js";

describe("Postgres SQL translation", () => {
  it("does not quote ALL-CAPS functions used by LDD UCase(Trim(Nom))", () => {
    const sql =
      "SELECT id FROM lookup_row WHERE table_key = ? AND UPPER(TRIM(nom)) = UPPER(TRIM(?))";
    const text = translateToPostgres(sql);
    expect(text).toContain("UPPER(TRIM(nom))");
    expect(text).toContain("UPPER(TRIM(");
    expect(text).not.toMatch(/"TRIM"/);
    expect(text).not.toMatch(/"UPPER"/);
  });

  it("still quotes PascalCase document columns", () => {
    const text = translateToPostgres(
      "SELECT Id, GroupeLigne, IndiceLigne FROM document WHERE GroupeLigne = ?",
    );
    expect(text).toContain('"Id"');
    expect(text).toContain('"GroupeLigne"');
    expect(text).toContain('"IndiceLigne"');
  });

  it("rewrites datetime('now') and INSERT OR IGNORE", () => {
    const dt = translateToPostgres("UPDATE app_lock SET locked_at = datetime('now') WHERE id = 1");
    expect(dt).toMatch(/\bNOW\s*\(\s*\)/i);
    const ins = translateToPostgres("INSERT OR IGNORE INTO lookup_table (table_key, label_fr) VALUES (?, ?)");
    expect(ins).toMatch(/INSERT INTO/i);
    expect(ins).toMatch(/ON CONFLICT DO NOTHING/i);
  });

  it("strips COLLATE NOCASE in DDL (Postgres has no NOCASE collation)", () => {
    const ddl = sqliteDdlToPostgres(
      "CREATE TABLE lookup_row (id INTEGER PRIMARY KEY AUTOINCREMENT, UNIQUE (table_key, nom COLLATE NOCASE))",
    );
    expect(ddl).not.toMatch(/NOCASE/i);
    expect(ddl).toMatch(/GENERATED BY DEFAULT AS IDENTITY/i);
  });
});

describe.skipIf(!process.env.DATABASE_URL)("Postgres live seed (DATABASE_URL)", () => {
  it("seeds and resolves CAF via UPPER(TRIM(nom))", async () => {
    const { default: pg } = await import("pg");
    const { PostgresDatabase, migrate } = await import("../src/sql.js");
    const { seed, lookupId } = await import("../src/seed.js");
    const url = new URL(process.env.DATABASE_URL as string);
    url.pathname = "/mi20_qa_seed";
    const admin = new pg.Pool({ connectionString: process.env.DATABASE_URL });
    await admin.query("DROP DATABASE IF EXISTS mi20_qa_seed");
    await admin.query("CREATE DATABASE mi20_qa_seed");
    await admin.end();
    const pool = new pg.Pool({ connectionString: url.toString() });
    const db = new PostgresDatabase(pool);
    try {
      await migrate(db);
      await seed(db, { extraDocs: 0 });
      const caf = await lookupId(db, "fournisseur", "caf");
      expect(caf).toBeGreaterThan(0);
    } finally {
      await db.close();
    }
  });
});
